### ISSUE TITLE
Issue to run code getting PCF8591 says no module

### ISSUE THREAD

**Issue by mkowndinya** [sunfounder/SunFounder_SensorKit_for_RPi2#1]
import PCF8591 as ADC
ImportError: No module named PCF8591

**Comment by sunfounder** [comment]
@mkowndinya That's weird, which directory did you run the code on?

**Comment by hijackindie** [comment]
I have a similar problem working with the sensor kit and a raspberry pi 3 running kernel 4.4.38-v7+.
Traceback (most recent call last):
  File "13_pcf8591.py", line 2, in <module>
    import PCF8591 as ADC
  File "/home/pi/SunFounder_SensorKit_for_RPi2/Python/PCF8591.py", line 23, in <module>
    bus = smbus.SMBus(1)
IOError: [Errno 2] No such file or directory

**Comment by hijackindie** [comment]
I got this working. I needed to enable I2C on the PI using raspi-config.

**Comment by sunfounder** [comment]
Yes, you need to enable I2C first, if you have any problems, welcome to post it on our forum: https://www.sunfounder.com/forum, or email us: support@sunfounder.com or of course, open an issue here.

**Comment by consolacion** [comment]
Ihave that same error:
import PCF8591 as ADC
ImportError: No module named PCF8591

Not surprising as I have no idea where to find and download the PCF8581 module, where can I find that?
I dont mean the pcd8591.py program, I mean the PCF8591 module

**Comment by hemalparikh123** [comment]
im getting an error 
line 44 in PCF8951.py 
return bus.read_byte(address)

what could i do to fix this?

**Comment by yosefgadban** [comment]
> I got this working. I needed to enable I2C on the PI using raspi-config.

I have a similar problem and i enabled I2C . still the same error

**Comment by SamGosselin** [comment]
Also having this issue. Code listed below:
`Traceback (most recent call last):
  File "18_thermistor.py", line 2, in <module>
    import PCF8591 as ADC
  File "/home/pi/SunFounder_SensorKit_for_RPi2/Python/PCF8591.py", line 23, in <module>
    bus = smbus.SMBus(1)
IOError: [Errno 2] No such file or directory`

If anyone knows a fix I would greatly appreciate a link or simple command.  Thanks.

**Comment by LuisValverde1296** [comment]
I'm also having troubles with this import, already enabled I2C and tried some other stuff I saw on different sources and still don't have a possitive result. If anyone has a propper fix please answer to my prayers. Thanks

**Comment by elijah247** [comment]
i am having the same problem, someone please answer!

**Comment by mschulz67** [comment]
If you're toying around with the sunfounder sensor kit: There's a file PCF8591.py (https://github.com/sunfounder/SunFounder_SensorKit_for_RPi2/blob/master/Python/PCF8591.py) that must be in the same directory as the executing script.
