### ISSUE TITLE
Raspberry Pi3 B+ Problem with BMP280

### ISSUE THREAD

**Issue by GK8591** [sunfounder/SunFounder_SensorKit_for_RPi2#6]
Hi, I've a problem with the connection of my Pi3 B+ with SunFounder Module BMP280
Thx for your help. Here is the error message:

pi@raspberrypi:~/SunFounder_SensorKit_for_RPi2/Python $ sudo python 31_bmp280.py                                                                                                                                                             
Traceback (most recent call last):
  File "31_bmp280.py", line 250, in <module>
    main()
  File "31_bmp280.py", line 231, in main
    bmp = BMP280()
  File "31_bmp280.py", line 108, in __init__
    self.bus_number = self._get_bus_number()
  File "31_bmp280.py", line 133, in _get_bus_number
    raise ValueError('Reading Pi type error, Your Pi "{0}"" is not in the list.\                                                                                                                                                             n  Please post an Issus at our Github Page or contract us\n    Github page: http                                                                                                                                                             s://github.com/sunfounder/Sunfounder_Smart_Video_Car_Kit_for_RaspberryPi/issues\                                                                                                                                                             n    Email: support@sunfounder.com\n    SunFounder'.format(pi_type))
ValueError: Reading Pi type error, Your Pi "Unknown"" is not in the list.
  Please post an Issus at our Github Page or contract us
    Github page: https://github.com/sunfounder/Sunfounder_Smart_Video_Car_Kit_fo                                                                                                                                                             r_RaspberryPi/issues
    Email: support@sunfounder.com
    SunFounder

pi@raspberrypi:~/SunFounder_SensorKit_for_RPi2/Python $ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- 77
pi@raspberrypi:~/SunFounder_SensorKit_for_RPi2/Python $

**Comment by martonz** [comment]
Had the same issue before, try to add 'Unknown' in  _BUS_1_TYPES list.

**Comment by GK8591** [comment]
Thanks a lot, I'll try this, good Idea.

It works, now 👍 Thanks
